// File: lib/firebase_options.dart
// This file is generated by FlutterFire CLI
// To regenerate, run: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGH3HZ9seRTbFyBAh-FqeMXnbAnB3wMq8',
    appId: '1:154250250063:web:cfe66c55514e0257a4a73a',
    messagingSenderId: '154250250063',
    projectId: 'terminal-application-5e0df',
    authDomain: 'terminal-application-5e0df.firebaseapp.com',
    storageBucket: 'terminal-application-5e0df.firebasestorage.app',
    measurementId: 'G-50JSG69XWC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8uM_oPGxeg14glCv9T4zDpklqHyeV9-Q',
    appId: '1:154250250063:ios:9b1e0dfd1b09957ea4a73a',
    messagingSenderId: '154250250063',
    projectId: 'terminal-application-5e0df',
    storageBucket: 'terminal-application-5e0df.firebasestorage.app',
    iosBundleId: 'com.example.musaffaTerminal',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGH3HZ9seRTbFyBAh-FqeMXnbAnB3wMq8',
    appId: '1:154250250063:web:cfe66c55514e0257a4a73a',
    messagingSenderId: '154250250063',
    projectId: 'terminal-application-5e0df',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGH3HZ9seRTbFyBAh-FqeMXnbAnB3wMq8',
    appId: '1:154250250063:web:cfe66c55514e0257a4a73a',
    messagingSenderId: '154250250063',
    projectId: 'terminal-application-5e0df',
  );
}