import 'package:flutter/material.dart';
import 'package:musaffa_terminal/Components/dynamic_table_reusable.dart';

/// Watchlist table columns: defaults stay on, extras can be added from Columns.
class WatchlistTableColumns {
  WatchlistTableColumns._();

  static const List<String> defaultVisibleKeys = <String>[
    'priceDisplay',
    'changeCell',
    'sparkline',
    'marketCap',
    'volume',
    'range52',
    'targetPrice',
    'notes',
  ];

  static List<SimpleColumn> all() {
    return const <SimpleColumn>[
      SimpleColumn(
        label: 'PRICE',
        fieldName: 'priceDisplay',
        isNumeric: true,
        width: 100,
        sortValueKey: 'currentPrice',
      ),
      SimpleColumn(
        label: 'CHANGE %',
        fieldName: 'changeCell',
        isNumeric: true,
        width: 110,
        sortValueKey: 'change1DPercent',
      ),
      SimpleColumn(
        label: '1D CHART',
        fieldName: 'sparkline',
        isNumeric: false,
        align: TextAlign.center,
        width: 104,
      ),
      SimpleColumn(
        label: 'MKT CAP',
        fieldName: 'marketCap',
        isNumeric: true,
        width: 112,
        sortValueKey: 'marketCapRaw',
      ),
      SimpleColumn(
        label: 'VOLUME',
        fieldName: 'volume',
        isNumeric: true,
        width: 96,
        sortValueKey: 'volumeRaw',
      ),
      SimpleColumn(
        label: '52W RANGE',
        fieldName: 'range52',
        isNumeric: false,
        align: TextAlign.center,
        width: 180,
      ),
      SimpleColumn(
        label: 'ALERTS',
        fieldName: 'targetPrice',
        isNumeric: false,
        align: TextAlign.center,
        width: 96,
      ),
      SimpleColumn(
        label: 'NOTES',
        fieldName: 'notes',
        isNumeric: false,
        align: TextAlign.center,
        width: 96,
      ),
      SimpleColumn(
        label: 'P/E',
        tooltipLabel: 'P/E (TTM)',
        fieldName: 'peTTM',
        isNumeric: true,
        width: 80,
        sortValueKey: 'peTTMSort',
      ),
      SimpleColumn(
        label: 'EPS',
        tooltipLabel: 'EPS (TTM)',
        fieldName: 'epsTTM',
        isNumeric: true,
        width: 88,
        sortValueKey: 'epsTTMSort',
      ),
      SimpleColumn(
        label: 'DIV YIELD',
        tooltipLabel: 'DIVIDEND YIELD',
        fieldName: 'dividendYield',
        isNumeric: true,
        width: 96,
        sortValueKey: 'dividendYieldSort',
      ),
      SimpleColumn(
        label: 'BETA',
        fieldName: 'beta',
        isNumeric: true,
        width: 76,
        sortValueKey: 'betaSort',
      ),
      SimpleColumn(
        label: 'AVG VOL',
        tooltipLabel: 'AVERAGE VOLUME (10D)',
        fieldName: 'avgVolume',
        isNumeric: true,
        width: 96,
        sortValueKey: 'avgVolumeSort',
      ),
      SimpleColumn(
        label: 'EXCHANGE',
        fieldName: 'exchange',
        isNumeric: false,
        width: 96,
      ),
      SimpleColumn(
        label: 'SECTOR',
        fieldName: 'sector',
        isNumeric: false,
        width: 140,
      ),
      SimpleColumn(
        label: 'INDUSTRY',
        fieldName: 'industry',
        isNumeric: false,
        width: 150,
      ),
      SimpleColumn(
        label: 'OPEN',
        fieldName: 'open',
        isNumeric: true,
        width: 88,
        sortValueKey: 'openSort',
      ),
      SimpleColumn(
        label: 'PREV CLOSE',
        tooltipLabel: 'PREVIOUS CLOSE',
        fieldName: 'previousClose',
        isNumeric: true,
        width: 104,
        sortValueKey: 'previousCloseSort',
      ),
      SimpleColumn(
        label: 'HIGH',
        fieldName: 'high',
        isNumeric: true,
        width: 88,
        sortValueKey: 'highSort',
      ),
      SimpleColumn(
        label: 'LOW',
        fieldName: 'low',
        isNumeric: true,
        width: 88,
        sortValueKey: 'lowSort',
      ),
      SimpleColumn(
        label: '52W HIGH',
        fieldName: 'weekHigh',
        isNumeric: true,
        width: 96,
        sortValueKey: 'weekHighSort',
      ),
      SimpleColumn(
        label: '52W LOW',
        fieldName: 'weekLow',
        isNumeric: true,
        width: 96,
        sortValueKey: 'weekLowSort',
      ),
      SimpleColumn(
        label: 'P/B',
        tooltipLabel: 'PRICE / BOOK',
        fieldName: 'pb',
        isNumeric: true,
        width: 76,
        sortValueKey: 'pbSort',
      ),
      SimpleColumn(
        label: 'ROE',
        tooltipLabel: 'RETURN ON EQUITY',
        fieldName: 'roe',
        isNumeric: true,
        width: 80,
        sortValueKey: 'roeSort',
      ),
      SimpleColumn(
        label: 'REV GROWTH',
        tooltipLabel: 'REVENUE GROWTH (TTM YOY)',
        fieldName: 'revGrowth',
        isNumeric: true,
        width: 110,
        sortValueKey: 'revGrowthSort',
      ),
      SimpleColumn(
        label: '1W %',
        tooltipLabel: '1 WEEK CHANGE',
        fieldName: 'change1W',
        isNumeric: true,
        width: 88,
        sortValueKey: 'change1WSort',
      ),
      SimpleColumn(
        label: '1M %',
        tooltipLabel: '1 MONTH CHANGE',
        fieldName: 'change1M',
        isNumeric: true,
        width: 88,
        sortValueKey: 'change1MSort',
      ),
      SimpleColumn(
        label: 'YTD %',
        tooltipLabel: 'YEAR TO DATE CHANGE',
        fieldName: 'changeYTD',
        isNumeric: true,
        width: 88,
        sortValueKey: 'changeYTDSort',
      ),
      SimpleColumn(
        label: 'ADDED PRICE',
        fieldName: 'addedPriceDisplay',
        isNumeric: true,
        width: 110,
        sortValueKey: 'addedPrice',
      ),
      SimpleColumn(
        label: 'GAIN / LOSS',
        fieldName: 'gainLossDisplay',
        isNumeric: true,
        width: 108,
        sortValueKey: 'gainLoss',
      ),
      SimpleColumn(
        label: 'G/L %',
        tooltipLabel: 'GAIN / LOSS %',
        fieldName: 'gainLossPercentDisplay',
        isNumeric: true,
        width: 88,
        sortValueKey: 'gainLossPercent',
      ),
    ];
  }
}
